### ISSUE TITLE
108 or 113 columns of cells?

### ISSUE THREAD

**Issue by pfranchini** [SuperNEMO-DBD/SuperNEMO-DBD.github.io#120]
In https://github.com/SuperNEMO-DBD/SuperNEMO-DBD.github.io/blob/master/about.md are reported 108 but have read 117 somewhere else.

**Comment by cherylepatrick** [comment]
Ha! It's 113. But I bet I didn't know that when I made the website. Thanks for pointing it out, will fix.

**Comment by cherylepatrick** [comment]
Fixed by #121 - @pfranchini do you want to see if you like the new version, and close it if so?

**Comment by pfranchini** [comment]
Thanks for that, this was an efficient ticket!
